/**
 * Final project
 * This is a final project for the course of Web Development
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Rate the game in given ladder
 */
export interface LadderRateRequest { 
    /**
     * Winner id
     */
    winner_id: number;
}

