/**
 * Final project
 * This is a final project for the course of Web Development
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Tournament } from './tournament';


/**
 * Ladder model
 */
export interface Ladder { 
    /**
     * Id
     */
    id: number;
    tournament: Tournament;
    participant1: User;
    participant2: User;
    /**
     * Winner id
     */
    winner_id: number;
}

