/**
 * Final project
 * This is a final project for the course of Web Development
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResetPasswordStoreRequest { 
    token: string;
    email: string;
    password: string;
    password_confirmation: string;
}

